#!/usr/bin/env python3
"""Export shared 16x16 UI masks as LVGL RGB565A8 assets."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'assets/images/h2h'
icons=json.loads((OUT/'icons.json').read_text())
source=['/* Generated by tools/h2h/build_icons.py; shared masks in icons.json. */','#include "lvgl.h"']
for name,rows in icons.items():
    assert len(rows)==16 and all(len(row)==16 and set(row)<={'.','#'} for row in rows)
    rgb=bytearray();alpha=bytearray()
    color=((0x26>>3)<<11)|((0x46>>2)<<5)|(0x6B>>3)
    for row in rows:
        for pixel in row:
            rgb.extend(color.to_bytes(2,'little'));alpha.append(255 if pixel=='#' else 0)
    source.append(f'static const uint8_t icon_{name}_data[]={{'+','.join(f'0x{x:02x}' for x in rgb+alpha)+'};')
    source.append(f'static const lv_image_dsc_t icon_{name}={{.header={{.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565A8,.w=16,.h=16,.stride=32}},.data_size=768,.data=icon_{name}_data}};')
source.append('const lv_image_dsc_t *const h2h_icons[4]={'+','.join('&icon_'+name for name in icons)+'};')
(OUT/'icons.c').write_text('\n'.join(source)+'\n')
print('4 shared 16x16 pixel icons exported (3072 bytes).')
