#!/usr/bin/env python3
"""Build local 16 kbps Opus resources; source audio is never modified."""
import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAX_AUDIO_BYTES = 5 * 1024 * 1024
PACKET_BYTES = 40  # 16 kbps CBR at 20 ms; reject any encoder output that differs.

def run(args):
    return subprocess.run(args, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

def opus_index(data):
    """Index our fixed 20 ms mono Ogg packets without changing encoded audio."""
    packets=[]; offset=0; headers=[]; pre_skip=0; final=None; sequence=0; serial=None
    while offset<len(data):
        if data[offset:offset+5]!=b'OggS\0' or offset+27>len(data): raise ValueError('Invalid Ogg page')
        flags=data[offset+5]; count=data[offset+26]; end_header=offset+27+count
        if end_header>len(data) or flags&1: raise ValueError('Unsupported continued Ogg packet')
        page_serial=int.from_bytes(data[offset+14:offset+18],'little')
        if serial is None: serial=page_serial
        if page_serial!=serial or int.from_bytes(data[offset+18:offset+22],'little')!=sequence: raise ValueError('Ogg stream discontinuity')
        sequence+=1; payload=end_header; length=0
        for lace in data[offset+27:end_header]:
            length+=lace
            if lace==255: continue
            if payload+length>len(data): raise ValueError('Truncated Opus packet')
            packet=data[payload:payload+length]
            if len(headers)<2:
                headers.append(packet)
                if len(headers)==1:
                    if len(packet)!=19 or packet[:8]!=b'OpusHead' or packet[8:10]!=bytes([1,1]) or packet[16:19]!=bytes(3): raise ValueError('Expected mono Opus with zero gain')
                    pre_skip=int.from_bytes(packet[10:12],'little')
                elif not packet.startswith(b'OpusTags'): raise ValueError('Missing OpusTags')
            else:
                if not packet or len(packet)>512: raise ValueError('Unexpected Opus packet size')
                config=packet[0]>>3; code=packet[0]&3
                samples=(120<<(config&3)) if config>=16 else (480<<(config&1)) if config>=12 else (480,960,1920,2880)[config&3]
                if code==3 and len(packet)<2: raise ValueError('Truncated Opus frame count')
                frames=1 if code==0 else 2 if code<3 else packet[1]&63
                if samples*frames!=960: raise ValueError('Expected 20 ms Opus packets')
                packets.append((payload,length))
            payload+=length; length=0
        if length: raise ValueError('Incomplete packet at page boundary')
        if flags&4:
            final=int.from_bytes(data[offset+6:offset+14],'little')
            if payload!=len(data): raise ValueError('Chained streams are not supported')
        offset=payload
    if final is None or not packets or not pre_skip<final<=len(packets)*960 or final<=(len(packets)-1)*960: raise ValueError('Invalid Opus end trim')
    return packets,pre_skip,final-pre_skip

def write_catalog(tracks,destination,song_count=None):
    song_count=len(tracks) if song_count is None else song_count
    if song_count<1 or song_count>len(tracks): raise ValueError('Invalid song count')
    if song_count != len(tracks):
        if len(tracks)!=2*song_count or any(tracks[i]['title']!=tracks[i+song_count]['title'] for i in range(song_count)):
            raise ValueError('Full songs and choruses must be paired in the same order.')
    source=['/* Generated by tools/h2h/pack_music.py. */','#include "h2h_tracks.h"']; indexes=[]
    flash_bytes=0
    for i,track in enumerate(tracks):
        data=(destination/track['file']).read_bytes()
        packets,pre_skip,pcm=opus_index(data)
        if any(length!=PACKET_BYTES for _,length in packets):
            raise ValueError(f'{track["file"]}: expected fixed {PACKET_BYTES}-byte Opus packets')
        raw=b''.join(data[offset:offset+length] for offset,length in packets)
        raw_name=f'track_{i:03}.bin'
        (destination/raw_name).write_bytes(raw)
        flash_bytes+=len(raw)
        indexes.append((len(packets),pre_skip,pcm));track['duration_ms']=round(pcm/48)
        track['packet_count']=len(packets);track['seek_index_bytes']=0
        track['flash_file']=raw_name;track['flash_bytes']=len(raw);track['flash_sha256']=hashlib.sha256(raw).hexdigest()
        source.append(f'extern const uint8_t _binary_track_{i:03}_bin_start[], _binary_track_{i:03}_bin_end[];')
    source.append('const h2h_track_t h2h_tracks[] = {')
    for i,track in enumerate(tracks):
        title,artist=(json.dumps(track[k],ensure_ascii=False) for k in ('title','artist'))
        n,pre,pcm=indexes[i]
        source.append(f'{{{title},{artist},{track["duration_ms"]},_binary_track_{i:03}_bin_start,_binary_track_{i:03}_bin_end,{n},{pre},{pcm},{PACKET_BYTES}}},')
    source+=['};',f'const unsigned h2h_track_count = {len(tracks)};',f'const unsigned h2h_song_count = {song_count};']
    (destination/'tracks.c').write_text('\n'.join(source)+'\n')
    cmake='\n'.join(f'target_add_binary_data(${{COMPONENT_LIB}} "${{CMAKE_CURRENT_LIST_DIR}}/{t["flash_file"]}" BINARY)' for t in tracks)
    (destination/'music.cmake').write_text(cmake+'\n')
    report={'encoding':'Opus CBR 16000 bps, mono, 48000 Hz, 20 ms','total_bytes':sum(t['bytes'] for t in tracks),'flash_audio_bytes':flash_bytes,'seek_index_bytes':0,'song_count':song_count,'tracks':tracks}
    (destination/'catalog.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps(report,ensure_ascii=False,indent=2))

def pack(entries, destination, song_count=None):
    if not entries or len(entries) > 99:
        raise ValueError('Choose between 1 and 99 tracks; packed audio must fit 5 MiB.')
    ffmpeg, ffprobe = shutil.which('ffmpeg'), shutil.which('ffprobe')
    if not ffmpeg or not ffprobe:
        raise ValueError('Install FFmpeg (ffmpeg and ffprobe) before packing music.')
    for entry in entries:
        if not Path(entry['file']).is_file():
            raise ValueError('Audio file not found: ' + entry['file'])
        for field in ('title', 'artist'):
            text = entry[field]
            if not isinstance(text, str) or not text.strip() or len(text) > 80 or any(ord(c) < 32 for c in text):
                raise ValueError('Title and artist must be 1–80 printable characters.')
    destination.mkdir(parents=True, exist_ok=True)
    tracks = []
    with tempfile.TemporaryDirectory(prefix='h2h-music-') as tmp:
        stage = Path(tmp)
        for index, entry in enumerate(entries):
            filename = f'track_{index:03}.ogg'
            out = stage / filename
            run([ffmpeg, '-v', 'error', '-nostdin', '-i', entry['file'], '-map_metadata', '-1',
                 '-vn', '-ac', '1', '-ar', '48000', '-c:a', 'libopus', '-b:a', '16k',
                 '-vbr', 'off', '-frame_duration', '20', '-application', 'audio', '-y', str(out)])
            info = json.loads(run([ffprobe, '-v', 'error', '-show_streams', '-show_format', '-of', 'json', str(out)]).stdout)
            stream = info['streams'][0]
            if stream['codec_name'] != 'opus' or stream['channels'] != 1 or int(stream['sample_rate']) != 48000:
                raise ValueError('Unexpected output format')
            run([ffmpeg, '-v', 'error', '-i', str(out), '-f', 'null', '-'])
            data = out.read_bytes()
            opus_index(data)
            tracks.append({'title': entry['title'], 'artist': entry['artist'], 'file': filename,
                           'duration_ms': round(float(info['format']['duration']) * 1000),
                           'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()})
        total = sum(t['bytes'] for t in tracks)
        if total > MAX_AUDIO_BYTES:
            raise ValueError(f'Encoded music uses {total} bytes; maximum is {MAX_AUDIO_BYTES}. Choose fewer songs.')
        # Publish only after all inputs convert and validate successfully.
        for track in tracks:
            shutil.copy2(stage / track['file'], destination / track['file'])
        write_catalog(tracks,destination,song_count)
    return tracks

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--manifest', type=Path, help='JSON list: [{file, title, artist}]; relative files resolve next to manifest')
    parser.add_argument('--input', type=Path)
    parser.add_argument('--reindex', action='store_true', help='Index existing packed Ogg files without re-encoding')
    parser.add_argument('--title', default='Lemon Tang')
    parser.add_argument('--artist', default='Hearts2Hearts')
    parser.add_argument('--song-count',type=int,help='Full songs in a paired full/chorus manifest')
    parser.add_argument('--output', type=Path, default=ROOT / 'assets/music/h2h')
    args = parser.parse_args()
    try:
        if args.reindex:
            catalog=json.loads((args.output/'catalog.json').read_text())
            write_catalog(catalog['tracks'],args.output,catalog.get('song_count'));return
        if args.manifest:
            entries = json.loads(args.manifest.read_text())
            for entry in entries:
                p = Path(entry['file']).expanduser()
                entry['file'] = str(p if p.is_absolute() else args.manifest.resolve().parent / p)
        elif args.input:
            entries = [{'file': str(args.input.expanduser()), 'title': args.title, 'artist': args.artist}]
        else:
            parser.error('Provide --input or --manifest')
        pack(entries, args.output,args.song_count)
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f'Music pack failed: {error}\n')
if __name__ == '__main__':
    main()
