/* Generated by tools/h2h/pack_music.py. */
#include "h2h_tracks.h"
extern const uint8_t _binary_track_000_bin_start[], _binary_track_000_bin_end[];
extern const uint8_t _binary_track_001_bin_start[], _binary_track_001_bin_end[];
extern const uint8_t _binary_track_002_bin_start[], _binary_track_002_bin_end[];
extern const uint8_t _binary_track_003_bin_start[], _binary_track_003_bin_end[];
extern const uint8_t _binary_track_004_bin_start[], _binary_track_004_bin_end[];
extern const uint8_t _binary_track_005_bin_start[], _binary_track_005_bin_end[];
extern const uint8_t _binary_track_006_bin_start[], _binary_track_006_bin_end[];
extern const uint8_t _binary_track_007_bin_start[], _binary_track_007_bin_end[];
extern const uint8_t _binary_track_008_bin_start[], _binary_track_008_bin_end[];
extern const uint8_t _binary_track_009_bin_start[], _binary_track_009_bin_end[];
extern const uint8_t _binary_track_010_bin_start[], _binary_track_010_bin_end[];
extern const uint8_t _binary_track_011_bin_start[], _binary_track_011_bin_end[];
extern const uint8_t _binary_track_012_bin_start[], _binary_track_012_bin_end[];
extern const uint8_t _binary_track_013_bin_start[], _binary_track_013_bin_end[];
const h2h_track_t h2h_tracks[] = {
{"Lemon Tang","Hearts2Hearts",163000,_binary_track_000_bin_start,_binary_track_000_bin_end,8151,312,7824000,40},
{"FOCUS","Hearts2Hearts",177052,_binary_track_001_bin_start,_binary_track_001_bin_end,8853,312,8498512,40},
{"ICONIC HEART","Hearts2Hearts",189000,_binary_track_002_bin_start,_binary_track_002_bin_end,9451,312,9072000,40},
{"Pretty Please","Hearts2Hearts",204322,_binary_track_003_bin_start,_binary_track_003_bin_end,10217,312,9807478,40},
{"RUDE!","Hearts2Hearts",200000,_binary_track_004_bin_start,_binary_track_004_bin_end,10001,312,9600000,40},
{"STYLE","Hearts2Hearts",209671,_binary_track_005_bin_start,_binary_track_005_bin_end,10484,312,10064217,40},
{"The Chase","Hearts2Hearts",178900,_binary_track_006_bin_start,_binary_track_006_bin_end,8946,312,8587210,40},
{"Lemon Tang","Hearts2Hearts",23352,_binary_track_007_bin_start,_binary_track_007_bin_end,1168,312,1120896,40},
{"FOCUS","Hearts2Hearts",36192,_binary_track_008_bin_start,_binary_track_008_bin_end,1810,312,1737216,40},
{"ICONIC HEART","Hearts2Hearts",45288,_binary_track_009_bin_start,_binary_track_009_bin_end,2265,312,2173824,40},
{"Pretty Please","Hearts2Hearts",31104,_binary_track_010_bin_start,_binary_track_010_bin_end,1556,312,1492992,40},
{"RUDE!","Hearts2Hearts",39216,_binary_track_011_bin_start,_binary_track_011_bin_end,1962,312,1882368,40},
{"STYLE","Hearts2Hearts",42888,_binary_track_012_bin_start,_binary_track_012_bin_end,2145,312,2058624,40},
{"The Chase","Hearts2Hearts",38184,_binary_track_013_bin_start,_binary_track_013_bin_end,1910,312,1832832,40},
};
const unsigned h2h_track_count = 14;
const unsigned h2h_song_count = 7;
